### ISSUE TITLE
Syntax Error hatası

### ISSUE THREAD

**Issue by androidprotmmas** [Camroku/cmfetch#1]
Merhabalar! cmfetch'in kurulumunu başarılı bir şekilde gerçekleştirdim. Ondan sonra cmfetch komutuyla cmfetch'i çalıştırmak istediğimde hata aldım. Ben de python3 cmfetch komutuyla cmfetch'i çalıştırmak istedim ve başarıyla çalıştırabildim.
Yardımcı olması için bir ekran görüntüsü gönderiyorum.
![cmfetch-hata](https://user-images.githubusercontent.com/82509753/131343667-76fc7074-acff-4c4f-8784-1936208362f5.png)

**Comment by Camroku** [comment]
`python /usr/bin/cmfetch` komutuyla da hata alıyor musun?

**Comment by Camroku** [comment]
Hatanın sebebi, Python sürümünün 3.x değil 2.x olarak çalışması. Düzeltiyorum.
